#pragma once
/*
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
1:  1
3:  1,3
6:  1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that  is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

int nrDivisor(long long n);

long long Problem() {
	int limit = 500;
	long long triNumber = 1;
	long long next = 2;
	while (nrDivisor(triNumber) <= limit) {
		triNumber += next++;
	}

	return triNumber;
}

int nrDivisor(long long n) {
    int count = 0;
    for (long long i = 1; i * i <= n; i++) {
        if (n % i == 0) {
            if (i * i == n) {
                count += 1;
            } else {
                count += 2;
            }
        }
    }
    return count;
}



