#pragma once
/*
* Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

long nextFibonacci(long prev, long current); 

long Problem() {
	long sumEven = 0;
	long limit = 4000000;
	
	long prev = 1;
	long current = 1;
	long tmp = current;

	current = nextFibonacci(prev, current);
	prev = tmp;
		
	while (current < limit) {
		if (current % 2 == 0) {
			sumEven += current;
		}
		
		tmp = current;
		current = nextFibonacci(prev, current);
		prev = tmp;
	}

	return (long) sumEven;
}

long nextFibonacci(long prev, long current) {
	return prev + current;
}

